apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-infra
  namespace: security-infra
spec:
  project: infra
  source:
    repoURL: https://github.com/monnierant/gitops
    path: security-infra
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: security-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
