apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian
  namespace: obsidian
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: "authentik-ak-outpost-traefik@kubernetescrd"
    traefik.ingress.kubernetes.io/router.priority: "10"
spec:
  rules:
    - host: obsidian.amonnier.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: obsidian
                port:
                  number: 3000
  tls:
    - hosts:
        - obsidian.amonnier.fr
      secretName: obsidian-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian-api
  namespace: obsidian
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: "obsidian-api-strip-jdr@kubernetescrd"
    traefik.ingress.kubernetes.io/router.priority: "20"
spec:
  rules:
    - host: obsidian.amonnier.fr
      http:
        paths:
          - path: /api/JDR
            pathType: Prefix
            backend:
              service:
                name: obsidian
                port:
                  number: 27123
  tls:
    - hosts:
        - obsidian.amonnier.fr
      secretName: obsidian-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: obsidian-api-strip-jdr
  namespace: obsidian
spec:
  stripPrefixRegex:
    regex:
      - "^/api/JDR/?"
