apiVersion: apps/v1
kind: Deployment
metadata:
  name: apikey-auth
  namespace: security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apikey-auth
  template:
    metadata:
      labels:
        app: apikey-auth
    spec:
      containers:
        - name: app
          image: tiangolo/uvicorn-gunicorn:python3.11
          env:
            - name: KEYSETS_JSON
              valueFrom:
                secretKeyRef:
                  name: api-gw-keysets
                  key: KEYSETS_JSON
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /healthz, port: 80 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: appcode
              mountPath: /app
      volumes:
        - name: appcode
          configMap:
            name: apikey-auth-app
