apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-configs
  namespace: mcp
data:
  mcp-config: ""
  mcp-tools: ""
  mcp-registry: |
    registry:
      notion:
        ref: ""
      playwright:
        ref: ""
